set_attack_value(AT_DSTRONG, AG_CATEGORY, 3);

set_attack_value(AT_DSTRONG, AG_SPRITE, sprite_get("dstrong"));

set_attack_value(AT_DSTRONG, AG_HURTBOX_SPRITE, sprite_get("dstrong_hurt"));

set_attack_value(AT_DSTRONG, AG_NUM_WINDOWS, 5);
ERROR_NO_SETTER_FOUND(AT_DSTRONG, MIN_TRAVEL_DISTANCE, 300);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_LENGTH, 20);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_SFX, asset_get("sfx_blow_weak2"));
set_window_value(AT_DSTRONG, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_LENGTH, 12);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_SFX, asset_get("sfx_blow_weak2"));
set_window_value(AT_DSTRONG, 5, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_DSTRONG, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_DSTRONG, COOLDOWN, 0);
set_num_hitboxes(AT_DSTRONG, 1);
//ERROR_NO_SETTER_FOUND(AT_DSTRONG, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_DSTRONG, 1, NUM, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_WINDOW, 3);
set_hitbox_value(AT_DSTRONG, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_LIFETIME, 9999);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DSTRONG, 1, HG_KNOCKBACK_SCALING, 0.60);
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE, 270);
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_DSTRONG, 1, HG_WIDTH, 50);
set_hitbox_value(AT_DSTRONG, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_X, 4);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_EFFECT, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DSTRONG, 1, HG_HITPAUSE_SCALING, 0.40);
set_hitbox_value(AT_DSTRONG, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DSTRONG, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_DSTRONG, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_DSTRONG, 1, HG_SHAPE, 0);
