set_attack_value(AT_BUBBLES, AG_CATEGORY, 3);

set_attack_value(AT_BUBBLES, AG_SPRITE, sprite_get("bubbles"));

set_attack_value(AT_BUBBLES, AG_HURTBOX_SPRITE, sprite_get("bubbles_hurt"));

set_attack_value(AT_BUBBLES, AG_NUM_WINDOWS, 1);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, HITSTUN, 2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, HITSTOP, 4);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, LOCKOUT_TIME, 6);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_V_KNOCKBACK, -2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_H_KNOCKBACK, 2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_V_KNOCKBACK, -5);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_H_KNOCKBACK, 1);
set_hitbox_value(AT_BUBBLES, 1, HG_DAMAGE, 2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_INPUT_DRIFT, 1);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_V_SPEED_RANGE, 2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_H_SPEED_MIN, 1);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, FAIR_H_SPEED_MAX, 3.50);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, BUBBLES_PER_FRAME_FAIR, 2);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_INPUT_DRIFT, 1.35);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_V_SPEED_MIN, 1);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_V_SPEED_MAX, 5);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, DSPECIAL_H_SPEED_RANGE, 1.50);
ERROR_NO_SETTER_FOUND(AT_BUBBLES, BUBBLES_PER_FRAME_DSPECIAL, 3);
