set_attack_value(AT_FSPECIAL_PUD, AG_CATEGORY, 3);

set_attack_value(AT_FSPECIAL_PUD, AG_SPRITE, sprite_get("fspecial_pud"));

set_attack_value(AT_FSPECIAL_PUD, AG_HURTBOX_SPRITE, sprite_get("fspecial_pud_hurt"));

set_attack_value(AT_FSPECIAL_PUD, AG_NUM_WINDOWS, 7);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_SFX, asset_get("sfx_orcane_fspecial_pud"));
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_HSPEED, 5);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_SFX, asset_get("sfx_orcane_fspecial_pud"));
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 4, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_LENGTH, 8);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 5, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_LENGTH, 2);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 6, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_SFX, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSPECIAL_PUD, 7, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FSPECIAL_PUD, HAS_COOLDOWN, 1);
//ERROR_NO_SETTER_FOUND(AT_FSPECIAL_PUD, COOLDOWN, 60);
set_num_hitboxes(AT_FSPECIAL_PUD, 1);
//ERROR_NO_SETTER_FOUND(AT_FSPECIAL_PUD, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_FSPECIAL_PUD, 1, NUM, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_WINDOW, 5);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_DAMAGE, 14);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_WIDTH, 100);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HEIGHT, 100);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HITBOX_X, -6);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HITBOX_Y, -22);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_EFFECT, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HITPAUSE_SCALING, 0.50);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_VISUAL_EFFECT, 150);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HIT_SFX, asset_get("sfx_waterhit_medium"));
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FSPECIAL_PUD, 1, HG_SHAPE, 0);
