set_attack_value(AT_UAIR, AG_CATEGORY, 1);

set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));

set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));

set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 3);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 13);
set_window_value(AT_UAIR, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_UAIR, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swish_heavy"));
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 3);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_UAIR, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 2);
set_window_value(AT_UAIR, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED, -3);
set_window_value(AT_UAIR, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_UAIR, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 11);
set_window_value(AT_UAIR, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_UAIR, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_UAIR, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_UAIR, COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_UAIR, HAS_WHIFF_LANDING, 8);
//ERROR_NO_SETTER_FOUND(AT_UAIR, AUTOCANCEL_FRAME, 40);
//ERROR_NO_SETTER_FOUND(AT_UAIR, LANDING_LAG, 8);
set_num_hitboxes(AT_UAIR, 2);
//ERROR_NO_SETTER_FOUND(AT_UAIR, NUM_UNIQUE_HITBOXES, 2);
//set_hitbox_value(AT_UAIR, 1, NUM, 0);
set_hitbox_value(AT_UAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_UAIR, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 3);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 11);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_UAIR, 2, HG_BASE_KNOCKBACK, 5);
ERROR_NO_SETTER_FOUND(AT_UAIR, 2, FINAL_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 2, HG_KNOCKBACK_SCALING, 0.60);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE, 270);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 11);
set_hitbox_value(AT_UAIR, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 30);
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 70);
set_hitbox_value(AT_UAIR, 2, HG_WIDTH, 50);
set_hitbox_value(AT_UAIR, 2, HG_HEIGHT, 20);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -75);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_UAIR, 1, HG_EFFECT, 0);
set_hitbox_value(AT_UAIR, 2, HG_EFFECT, 0);
set_hitbox_value(AT_UAIR, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_UAIR, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_UAIR, 2, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_UAIR, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 2, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 8);
set_hitbox_value(AT_UAIR, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_UAIR, 2, HG_HITPAUSE_SCALING, 0.20);
set_hitbox_value(AT_UAIR, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_UAIR, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT, 195);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT, 150);
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT_Y_OFFSET, 16);
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_UAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_UAIR, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_UAIR, 2, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_UAIR, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_UAIR, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_UAIR, 1, HG_HIT_LOCKOUT, 18);
set_hitbox_value(AT_UAIR, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_UAIR, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_UAIR, 2, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_UAIR, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_UAIR, 2, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_UAIR, 1, HG_SHAPE, 0);
set_hitbox_value(AT_UAIR, 2, HG_SHAPE, 0);
