set_attack_value(AT_USTRONG_PUD, AG_CATEGORY, 3);

set_attack_value(AT_USTRONG_PUD, AG_SPRITE, sprite_get("ustrong_pud"));

set_attack_value(AT_USTRONG_PUD, AG_HURTBOX_SPRITE, sprite_get("ustrong_pud_hurt"));

set_attack_value(AT_USTRONG_PUD, AG_NUM_WINDOWS, 4);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USTRONG_PUD, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_LENGTH, 13);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_SFX, asset_get("sfx_swish_heavy2"));
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_SFX_FRAME, 3);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USTRONG_PUD, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_LENGTH, 8);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USTRONG_PUD, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_LENGTH, 23);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_SFX, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_HAS_WHIFFLAG, 12);
set_window_value(AT_USTRONG_PUD, 4, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_USTRONG_PUD, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_USTRONG_PUD, COOLDOWN, 0);
set_num_hitboxes(AT_USTRONG_PUD, 1);
//ERROR_NO_SETTER_FOUND(AT_USTRONG_PUD, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_USTRONG_PUD, 1, NUM, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_WINDOW, 3);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_LIFETIME, 8);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_BASE_KNOCKBACK, 10);
ERROR_NO_SETTER_FOUND(AT_USTRONG_PUD, 1, FINAL_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_KNOCKBACK_SCALING, 1.30);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_ANGLE, 90);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_DAMAGE, 14);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_WIDTH, 40);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HEIGHT, 136);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HITBOX_X, 5);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HITBOX_Y, -97);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_EFFECT, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_VISUAL_EFFECT, 161);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_VISUAL_EFFECT_Y_OFFSET, -32);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HIT_SFX, asset_get("sfx_waterhit_heavy2"));
set_hitbox_value(AT_USTRONG_PUD, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HIT_LOCKOUT, 10);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_USTRONG_PUD, 1, HG_SHAPE, 1);
