set_attack_value(AT_FSTRONG, AG_CATEGORY, 3);

set_attack_value(AT_FSTRONG, AG_SPRITE, sprite_get("fstrong"));

set_attack_value(AT_FSTRONG, AG_HURTBOX_SPRITE, sprite_get("fstrong_hurt"));

set_attack_value(AT_FSTRONG, AG_NUM_WINDOWS, 4);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_LENGTH, 2);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HSPEED, 5);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_LENGTH, 2);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_LENGTH, 20);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_SFX, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_HAS_WHIFFLAG, 8);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FSTRONG, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FSTRONG, COOLDOWN, 0);
set_num_hitboxes(AT_FSTRONG, 1);
//ERROR_NO_SETTER_FOUND(AT_FSTRONG, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_FSTRONG, 1, NUM, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW, 3);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSTRONG, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE, 361);
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_DAMAGE, 10);
set_hitbox_value(AT_FSTRONG, 1, HG_WIDTH, 92);
set_hitbox_value(AT_FSTRONG, 1, HG_HEIGHT, 48);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_X, 36);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_Y, -26);
set_hitbox_value(AT_FSTRONG, 1, HG_EFFECT, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_PRIORITY, 7);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSTRONG, 1, HG_HITPAUSE_SCALING, 0.70);
set_hitbox_value(AT_FSTRONG, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT, 110);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT_X_OFFSET, 23);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_HIT_SFX, asset_get("sfx_ori_energyhit_heavy"));
set_hitbox_value(AT_FSTRONG, 1, HG_EXTRA_CAMERA_SHAKE, 2);
set_hitbox_value(AT_FSTRONG, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_SHAPE, 0);
