set_attack_value(AT_FAIR, AG_CATEGORY, 1);

set_attack_value(AT_FAIR, AG_SPRITE, sprite_get("fair"));

set_attack_value(AT_FAIR, AG_HURTBOX_SPRITE, sprite_get("fair_hurt"));

set_attack_value(AT_FAIR, AG_NUM_WINDOWS, 3);
set_window_value(AT_FAIR, 1, AG_WINDOW_LENGTH, 11);
set_window_value(AT_FAIR, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_FAIR, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX_FRAME, 7);
set_window_value(AT_FAIR, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FAIR, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_LENGTH, 13);
set_window_value(AT_FAIR, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 8);
set_window_value(AT_FAIR, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, HAS_WHIFF_LANDING, 6);
//ERROR_NO_SETTER_FOUND(AT_FAIR, AUTOCANCEL_FRAME, 15);
//ERROR_NO_SETTER_FOUND(AT_FAIR, LANDING_LAG, 8);
set_num_hitboxes(AT_FAIR, 1);
//ERROR_NO_SETTER_FOUND(AT_FAIR, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_FAIR, 1, NUM, 0);
set_hitbox_value(AT_FAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FAIR, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_FAIR, 1, HG_BASE_KNOCKBACK, 6);
ERROR_NO_SETTER_FOUND(AT_FAIR, 1, FINAL_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FAIR, 1, HG_KNOCKBACK_SCALING, 0.85);
set_hitbox_value(AT_FAIR, 1, HG_ANGLE, 40);
set_hitbox_value(AT_FAIR, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FAIR, 1, HG_DAMAGE, 11);
set_hitbox_value(AT_FAIR, 1, HG_WIDTH, 70);
set_hitbox_value(AT_FAIR, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_X, 55);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FAIR, 1, HG_EFFECT, 0);
set_hitbox_value(AT_FAIR, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FAIR, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FAIR, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FAIR, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_FAIR, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FAIR, 1, HG_HITPAUSE_SCALING, 0.50);
set_hitbox_value(AT_FAIR, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FAIR, 1, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_FAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, 10);
set_hitbox_value(AT_FAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FAIR, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_FAIR, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FAIR, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FAIR, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FAIR, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FAIR, 1, HG_SHAPE, 0);
