set_attack_value(AT_DSPECIAL_SUMMON, AG_CATEGORY, 3);

set_attack_value(AT_DSPECIAL_SUMMON, AG_SPRITE, sprite_get("dspecial_summon"));

set_attack_value(AT_DSPECIAL_SUMMON, AG_HURTBOX_SPRITE, sprite_get("dspecial_summon_hurt"));

set_attack_value(AT_DSPECIAL_SUMMON, AG_NUM_WINDOWS, 2);
ERROR_NO_SETTER_FOUND(AT_DSPECIAL_SUMMON, BUBBLE_SUMMON_ACCEL, 0.50);
ERROR_NO_SETTER_FOUND(AT_DSPECIAL_SUMMON, BUBBLE_SUMMON_SPEED, 9);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_SFX, asset_get("sfx_frog_nspecial_shove"));
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_SFX_FRAME, 4);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL_SUMMON, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_LENGTH, 5);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL_SUMMON, 2, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL_SUMMON, HAS_COOLDOWN, 1);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL_SUMMON, COOLDOWN, 60);
set_num_hitboxes(AT_DSPECIAL_SUMMON, 0);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL_SUMMON, NUM_UNIQUE_HITBOXES, 0);
//set_hitbox_value(AT_DSPECIAL_SUMMON, 1, NUM, 0);
