set_attack_value(AT_DSPECIAL, AG_CATEGORY, 2);

set_attack_value(AT_DSPECIAL, AG_SPRITE, sprite_get("dspecial"));

set_attack_value(AT_DSPECIAL, AG_HURTBOX_SPRITE, sprite_get("dspecial_hurt"));

set_attack_value(AT_DSPECIAL, AG_NUM_WINDOWS, 4);
ERROR_NO_SETTER_FOUND(AT_DSPECIAL, BUBBLE_LIFETIME, 900);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_SFX, asset_get("sfx_frog_nspecial_cast"));
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_SFX_FRAME, 5);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_LENGTH, 30);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_SFX, asset_get("sfx_frog_nspecial_shove"));
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_SFX_FRAME, 5);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL, HAS_COOLDOWN, 1);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL, COOLDOWN, 20);
set_num_hitboxes(AT_DSPECIAL, 0);
//ERROR_NO_SETTER_FOUND(AT_DSPECIAL, NUM_UNIQUE_HITBOXES, 0);
//set_hitbox_value(AT_DSPECIAL, 1, NUM, 0);
