set_attack_value(AT_FAIR, AG_CATEGORY, 1);

set_attack_value(AT_FAIR, AG_SPRITE, sprite_get("fair"));

set_attack_value(AT_FAIR, AG_HURTBOX_SPRITE, sprite_get("fair_hurt"));

set_attack_value(AT_FAIR, AG_NUM_WINDOWS, 3);
ERROR_NO_SETTER_FOUND(AT_FAIR, ARMOR_VALUE, 12);
ERROR_NO_SETTER_FOUND(AT_FAIR, MIN_ARMOR_FRAMES, 7);
set_window_value(AT_FAIR, 1, AG_WINDOW_LENGTH, 1);
set_window_value(AT_FAIR, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FAIR, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_LENGTH, 30);
set_window_value(AT_FAIR, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FAIR, 2, AG_WINDOW_SFX, asset_get("sfx_ice_shieldup"));
set_window_value(AT_FAIR, 2, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_FAIR, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FAIR, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FAIR, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FAIR, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, HAS_WHIFF_LANDING, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, AUTOCANCEL_FRAME, 1);
//ERROR_NO_SETTER_FOUND(AT_FAIR, LANDING_LAG, 3);
set_num_hitboxes(AT_FAIR, 0);
//ERROR_NO_SETTER_FOUND(AT_FAIR, NUM_UNIQUE_HITBOXES, 0);
//set_hitbox_value(AT_FAIR, 1, NUM, 0);
