set_attack_value(AT_USPECIAL, AG_CATEGORY, 2);

set_attack_value(AT_USPECIAL, AG_SPRITE, sprite_get("uspecial"));

set_attack_value(AT_USPECIAL, AG_HURTBOX_SPRITE, sprite_get("uspecial_hurt"));

set_attack_value(AT_USPECIAL, AG_NUM_WINDOWS, 4);
ERROR_NO_SETTER_FOUND(AT_USPECIAL, MIN_ACTIONABLE_SPEED, -8);
ERROR_NO_SETTER_FOUND(AT_USPECIAL, MAX_BOOST, 22);
ERROR_NO_SETTER_FOUND(AT_USPECIAL, MIN_BOOST, 11);
ERROR_NO_SETTER_FOUND(AT_USPECIAL, MAX_CHARGE_TIME, 56);
ERROR_NO_SETTER_FOUND(AT_USPECIAL, MIN_CHARGE_TIME, 6);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_LENGTH, 4);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_SFX, asset_get("sfx_ice_uspecial_start"));
set_window_value(AT_USPECIAL, 1, AG_WINDOW_SFX_FRAME, 2);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_LENGTH, 60);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_LENGTH, 9);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_SFX, asset_get("sfx_ice_uspecial_jump"));
set_window_value(AT_USPECIAL, 3, AG_WINDOW_SFX_FRAME, 3);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_LENGTH, 900);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_SFX, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL, 4, AG_WINDOW_INVINCIBILITY, 2);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL, COOLDOWN, 0);
set_num_hitboxes(AT_USPECIAL, 1);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_USPECIAL, 1, NUM, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_USPECIAL, 1, HG_WINDOW, 3);
set_hitbox_value(AT_USPECIAL, 1, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_USPECIAL, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_USPECIAL, 1, HG_KNOCKBACK_SCALING, 0.60);
set_hitbox_value(AT_USPECIAL, 1, HG_ANGLE, 270);
set_hitbox_value(AT_USPECIAL, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USPECIAL, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_USPECIAL, 1, HG_WIDTH, 80);
set_hitbox_value(AT_USPECIAL, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_Y, 20);
set_hitbox_value(AT_USPECIAL, 1, HG_EFFECT, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_USPECIAL, 1, HG_HITPAUSE_SCALING, 0.40);
set_hitbox_value(AT_USPECIAL, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_VISUAL_EFFECT, 29);
set_hitbox_value(AT_USPECIAL, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_USPECIAL, 1, HG_HIT_SFX, asset_get("sfx_icehit_medium1"));
set_hitbox_value(AT_USPECIAL, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_USPECIAL, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_SHAPE, 0);
