set_attack_value(AT_USPECIAL_MARKED, AG_CATEGORY, 3);

set_attack_value(AT_USPECIAL_MARKED, AG_SPRITE, sprite_get("uspecial_marked"));

set_attack_value(AT_USPECIAL_MARKED, AG_HURTBOX_SPRITE, sprite_get("uspecial_marked_hurt"));

set_attack_value(AT_USPECIAL_MARKED, AG_NUM_WINDOWS, 3);
ERROR_NO_SETTER_FOUND(AT_USPECIAL_MARKED, BASE_SLING_TIME, 6);
ERROR_NO_SETTER_FOUND(AT_USPECIAL_MARKED, SLING_DISTANCE_DIVISOR, 40);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_LENGTH, 14);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL_MARKED, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_USPECIAL_MARKED, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USPECIAL_MARKED, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_USPECIAL_MARKED, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USPECIAL_MARKED, 2, AG_WINDOW_INVINCIBILITY, 2);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_LENGTH, 7);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_SFX, asset_get("sfx_upbmove"));
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_USPECIAL_MARKED, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL_MARKED, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL_MARKED, COOLDOWN, 0);
set_num_hitboxes(AT_USPECIAL_MARKED, 0);
//ERROR_NO_SETTER_FOUND(AT_USPECIAL_MARKED, NUM_UNIQUE_HITBOXES, 0);
//set_hitbox_value(AT_USPECIAL_MARKED, 1, NUM, 0);
