set_attack_value(AT_FTILT, AG_CATEGORY, 3);

set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));

set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));

set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 3);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_FTILT, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX, asset_get("sfx_clairen_swing_med"));
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX_FRAME, 6);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 15);
set_window_value(AT_FTILT, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 5);
set_window_value(AT_FTILT, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FTILT, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FTILT, COOLDOWN, 0);
set_num_hitboxes(AT_FTILT, 2);
//ERROR_NO_SETTER_FOUND(AT_FTILT, NUM_UNIQUE_HITBOXES, 2);
//set_hitbox_value(AT_FTILT, 1, NUM, 0);
set_hitbox_value(AT_FTILT, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FTILT, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, 0.50);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, 0.60);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 361);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 40);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 7);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 92);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 72);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 104);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 74);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X, 58);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -33);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X, 75);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 1, HG_EFFECT, 0);
set_hitbox_value(AT_FTILT, 2, HG_EFFECT, 11);
set_hitbox_value(AT_FTILT, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FTILT, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FTILT, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FTILT, 2, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FTILT, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FTILT, 2, HG_TECHABLE, 0);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FTILT, 1, HG_HITPAUSE_SCALING, 0.50);
set_hitbox_value(AT_FTILT, 2, HG_HITPAUSE_SCALING, 0.70);
set_hitbox_value(AT_FTILT, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FTILT, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, 123);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, 125);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_X_OFFSET, 30);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_X_OFFSET, 45);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_clairen_hit_med"));
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_clairen_tip_med"));
set_hitbox_value(AT_FTILT, 1, HG_EXTRA_CAMERA_SHAKE, 2);
set_hitbox_value(AT_FTILT, 2, HG_EXTRA_CAMERA_SHAKE, 2);
set_hitbox_value(AT_FTILT, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FTILT, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FTILT, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FTILT, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FTILT, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FTILT, 2, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FTILT, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FTILT, 2, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FTILT, 1, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 2, HG_SHAPE, 0);
