set_attack_value(AT_FTILT, AG_CATEGORY, 3);

set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));

set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));

set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 4);
ERROR_NO_SETTER_FOUND(AT_FTILT, MAX_RANGE, 638);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_FTILT, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_SFX, asset_get("sfx_absa_new_whip1"));
set_window_value(AT_FTILT, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 3, AG_WINDOW_CANCEL_FRAME, 4);
set_window_value(AT_FTILT, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 11);
set_window_value(AT_FTILT, 3, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 4, AG_WINDOW_SFX, asset_get("sfx_absa_whip_charge"));
set_window_value(AT_FTILT, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_FTILT, 4, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FTILT, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_FTILT, COOLDOWN, 0);
set_num_hitboxes(AT_FTILT, 2);
//ERROR_NO_SETTER_FOUND(AT_FTILT, NUM_UNIQUE_HITBOXES, 2);
//set_hitbox_value(AT_FTILT, 1, NUM, 0);
set_hitbox_value(AT_FTILT, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FTILT, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 5);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 12);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, 0.30);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 70);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 85);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 96);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 66);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 0);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 0);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X, 32);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X, 26);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -40);
set_hitbox_value(AT_FTILT, 1, HG_EFFECT, 0);
set_hitbox_value(AT_FTILT, 2, HG_EFFECT, 0);
set_hitbox_value(AT_FTILT, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FTILT, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_FTILT, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_FTILT, 2, HG_HITSTUN_MULTIPLIER, 0.50);
set_hitbox_value(AT_FTILT, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FTILT, 2, HG_TECHABLE, 0);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FTILT, 1, HG_HITPAUSE_SCALING, 0.20);
set_hitbox_value(AT_FTILT, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FTILT, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FTILT, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, 21);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_Y_OFFSET, 10);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_absa_harderhit"));
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_absa_harderhit"));
set_hitbox_value(AT_FTILT, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_FTILT, 2, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_FTILT, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FTILT, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FTILT, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FTILT, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FTILT, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FTILT, 2, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_FTILT, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_FTILT, 2, HG_FORCE_FLINCH, 3);
set_hitbox_value(AT_FTILT, 1, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 2, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_MASK, 1);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_GRAVITY, 0);
//ERROR_NO_SETTER_FOUND(AT_FTILT, 2, PROJECTILE_LIFETIME, 12);
