set_attack_value(AT_JAB, AG_CATEGORY, 3);

set_attack_value(AT_JAB, AG_SPRITE, sprite_get("jab"));

set_attack_value(AT_JAB, AG_HURTBOX_SPRITE, sprite_get("jab_hurt"));

set_attack_value(AT_JAB, AG_NUM_WINDOWS, 3);
set_window_value(AT_JAB, 1, AG_WINDOW_LENGTH, 4);
set_window_value(AT_JAB, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_JAB, 1, AG_WINDOW_SFX, asset_get("sfx_bite"));
set_window_value(AT_JAB, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_JAB, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_LENGTH, 2);
set_window_value(AT_JAB, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_SFX, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_JAB, 2, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_LENGTH, 13);
set_window_value(AT_JAB, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_SFX, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_JAB, 3, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_JAB, 3, AG_WINDOW_INVINCIBILITY, 0);
//ERROR_NO_SETTER_FOUND(AT_JAB, HAS_COOLDOWN, 0);
//ERROR_NO_SETTER_FOUND(AT_JAB, COOLDOWN, 0);
set_num_hitboxes(AT_JAB, 1);
//ERROR_NO_SETTER_FOUND(AT_JAB, NUM_UNIQUE_HITBOXES, 1);
//set_hitbox_value(AT_JAB, 1, NUM, 0);
set_hitbox_value(AT_JAB, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_JAB, 1, HG_WINDOW, 2);
set_hitbox_value(AT_JAB, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_JAB, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_JAB, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_JAB, 1, HG_KNOCKBACK_SCALING, 0.55);
set_hitbox_value(AT_JAB, 1, HG_ANGLE, 361);
set_hitbox_value(AT_JAB, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_JAB, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_JAB, 1, HG_WIDTH, 74);
set_hitbox_value(AT_JAB, 1, HG_HEIGHT, 40);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_X, 49);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_Y, -43);
set_hitbox_value(AT_JAB, 1, HG_EFFECT, 0);
set_hitbox_value(AT_JAB, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_JAB, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_JAB, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_JAB, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_JAB, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_JAB, 1, HG_HITPAUSE_SCALING, 0.50);
set_hitbox_value(AT_JAB, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_JAB, 1, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_JAB, 1, HG_VISUAL_EFFECT_X_OFFSET, 16);
set_hitbox_value(AT_JAB, 1, HG_VISUAL_EFFECT_Y_OFFSET, 4);
set_hitbox_value(AT_JAB, 1, HG_HIT_SFX, asset_get("sfx_crunch"));
set_hitbox_value(AT_JAB, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_JAB, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_JAB, 1, HG_HIT_LOCKOUT, 6);
set_hitbox_value(AT_JAB, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_JAB, 1, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_JAB, 1, HG_SHAPE, 0);
